defaults:
    box: generic/centos8
    memory: 2048
    cpus: 1
    use_ansible_local: true
servers:
    - name: server1
      hostname: server1.lab.com
      cpus: 2
      ip: 192.168.56.100
      forward:
          - guest: 80
            host: 8080
    - name: ansible
      hostname: ansible.lab.com
      memory: 1024
      ip: 192.168.56.101
      ansible:
          playbook: playbook.yml
          inventory: inventory
          limit: all,localhost
