- name: Ping all the things!
  #For server1
  hosts: ftpserver
  connection: local 
  tasks:
      - ping:

- name: Setup FTP-server
  hosts: ftpserver
  connection: local 
  become: yes
  tasks:
    - name: "Install {{ packages }}"
      yum:
        state: present 
        name: "{{ packages }}"
      vars:
        packages:
          - vsftpd
          - nfs-utils
    - name: Enable service in firewalld
      firewalld:
        port: 21/tcp
        permanent: yes
        state: enabled
    - name: Enable service in firewalld
      firewalld:
        service: ftp
        permanent: yes
        state: enabled
    - name: Relead firewalld
      command: firewall-cmd --reload
      register: output
    - name: Make sure selinux is correct
      command: setsebool -P tftp_home_dir on
    - name: Make sure a service is running
      systemd:
        state: started
        enabled: yes
        name: vsftpd
    - name: Make sure a service is running
      systemd:
        state: started
        enabled: yes
        name: nfs-server
    - name: Enable NFS service in firewalld
      firewalld:
        port: 2049/tcp
        permanent: yes
        state: enabled
    - name: Enable NFS service in firewalld
      firewalld:
        port: 2049/udp
        permanent: yes
        state: enabled
    - name: Enable NFS service in firewalld
      firewalld:
        port: 111/tcp
        permanent: yes
        state: enabled
    - name: Relead firewalld
      command: firewall-cmd --reload

    - name: Ensure data folder is present
      file:
        path: /data/ftp
        #owner: foo
        #group: foo
        mode: '0777'
        state: directory
    - name: Ensure data folder is present
      file:
        path: /data/nfsshare/
        #owner: foo
        #group: foo
        mode: '0777'
        state: directory
    - name: Create FTP group 
      group:
        name: ftpgroup
        state: present
    - name: Create FTP user
      user:
        name: ftpuser
        password: ftpuser
        shell: /bin/bash
        group: ftpgroup
        #home: /data/ftp/$USER
        append: yes
        update_password: always
    - name: Add line to exportfs
      lineinfile:
        path: /etc/exports
        #state: present
        regexp: '^/data/nfsshare'
        line: '/data/nfsshare *(rw)'
    - name: Export share
      command: exportfs -a