Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"

  config.vm.define "checkmk", primary: true do |vm1|
    vm1.vm.network "private_network", ip: "192.168.56.101"
    vm1.vm.network "forwarded_port", guest: 80, host: 8080,
      auto_correct: true
    vm1.vm.provider "virtualbox" do |vb|
      vb.name = "checkmk.lab.com"
      vb.gui = false
      vb.memory = "3072"
      vb.cpus = 1
      # To solve dns resovling issue https://askubuntu.com/questions/238040/how-do-i-fix-name-service-for-vagrant-client & https://serverfault.com/questions/453185/vagrant-virtualbox-dns-10-0-2-3-not-working
      # vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    end
    vm1.vm.hostname = "checkmk.lab.com"
    # Sync folder documentation https://www.vagrantup.com/docs/synced-folders/rsync.html
    config.vm.synced_folder "./install-check_mk-server", "/etc/ansible/roles/install-check_mk-server", type: "rsync"
    
    config.vm.provision "ansible_local" do |ansible|
      ansible.limit = "all,localhost"
      ansible.playbook = "checkmk_playbook.yml"
    end
    vm1.vm.provision "shell",
      inline: "/usr/sbin/setsebool -P httpd_can_network_connect 1"
  end
  
  config.vm.define "ansible" do |vm2|
    vm2.vm.network "private_network", ip: "192.168.56.102"
    vm2.vm.provider "virtualbox" do |vb|
      vb.name = "ansible.lab.com"
      vb.gui = false
      vb.memory = "1024"
      vb.cpus = 1
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    end
    # The hostname the machine should have. See: vagrant ssh
    vm2.vm.hostname = "ansible.lab.com"

    config.vm.synced_folder "./ansible-checkmk/roles/", "/etc/ansible/roles/", type: "rsync"
    config.vm.synced_folder "./ansible-role-check-mk-agent", "/etc/ansible/roles/ansible-role-check-mk-agent", type: "rsync"
    config.vm.provision "ansible_local" do |ansible|
      ansible.limit = "all,localhost"
      ansible.playbook = "add_host_to_checkmk_playbook.yml"
    end
  end
  
end