Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"

  config.vm.define "checkmk", primary: true do |vm1|
    vm1.vm.network "private_network", ip: "192.168.56.101"
    vm1.vm.network "forwarded_port", guest: 80, host: 8080,
      auto_correct: true
    vm1.vm.provider "virtualbox" do |vb|
      vb.name = "webserver.lab.com"
      vb.gui = false
      vb.memory = "2048
      vb.cpus = 1
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    end
    vm1.vm.hostname = "webserver.lab.com"
  end
  
  config.vm.define "ansible" do |vm2|
    vm2.vm.network "private_network", ip: "192.168.56.102"
    vm2.vm.provider "virtualbox" do |vb|
      vb.name = "ansible.lab.com"
      vb.gui = false
      vb.memory = "1024"
      vb.cpus = 1
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    end
    # The hostname the machine should have. See: vagrant ssh
    vm2.vm.hostname = "ansible.lab.com"

    config.vm.synced_folder "./ansible-role", "/etc/ansible/roles/ansible-role", type: "rsync"
 #   config.vm.provision "ansible_local" do |ansible|
 #     ansible.limit = "all,localhost"
 #     ansible.playbook = "add_host_to_checkmk_playbook.yml"
 #   end
  end
  
end